---
apiVersion: v1
kind: Service
metadata:
  name: vote             #sevice name is important, catioud as it auto sets the DNS entry
  labels:
    app: vote
spec:
  type: NodePort
  ports:
    - targetPort: 80           # pod/container/target port
      port: 80     # servicePort - generally keep same as targetPort
      nodePort: 31000
      name: "vote-service"
  selector:
    app: vote
    tier: front-end