---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-redis
  labels:
    app: redis
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      tier: database
  template:
    metadata:
      name: redis              #myapp-redis
      labels:
        app: redis
        tier: database
    spec:
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379         #target/container/pod/backend Port
              name: redis