---
apiVersion: v1
kind: Pod
metadata:
  name: redis              #myapp-redis
  labels:
    app: redis
    tier: database
spec:
  containers:
    - name: redis
      image: redis:alpine
      ports:
        - containerPort: 6379         #target/container/pod/backend Port
          name: redis