---
apiVersion: v1
kind: Service
metadata:
  name: result             #sevice name is important, catioud as it auto sets the DNS entry
  labels:
    app: result
spec:
  type: NodePort
  ports:
    - targetPort: 80           # pod/container/target port
      port: 80     # servicePort - generally keep same as targetPort
      nodePort: 31001
      name: "result-service"
  selector:
    app: result
    tier: front-end
 
# Since this is the last service, once done hit below commands:
  # kubectl apply -f .
  # kubectl get po
  # kubectl get svc
  # kubectl get node -o wide   #pick nodeIP
     # In google, nodeIP:nodeport access  vote and result app
          # vote app- nodeIP:vote_nodePort and result app - nodeIP:result_nodePort