---
apiVersion: v1
kind: Pod
metadata:
  name: worker         #myapp-worker
  labels:
    app: worker
    tier: backend
spec:
  containers:
    - name: worker
      image: postgres:15-alpine
    # ports: no, service not exposed 