---
apiVersion: v1
kind: Service
metadata:
  name: db             #sevice name is important, catioud as it auto sets the DNS entry
  labels:
    app: db
spec:
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432     # generally keep same as targetPort
      name: "db-service"
  selector:
    app: db
    tier: database