---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-db
  labels:
    app: db
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
      tier: database
  template:
    metadata:
      name: db         #myapp-db-postgres
      labels:
        app: db
        tier: database
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432         #targetPort
              name: postgres