--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
      tier: backend
  template:
    metadata:
      name: worker         #myapp-worker
      labels:
        app: worker
        tier: backend
    spec:
      containers:
        - name: worker
          image: postgres:15-alpine
        # ports: no, service not exposed  
 